name: Automatic comment on the latest PR

on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'    
      
      - name: Comment on the latest PR
        run: |
          pip install requests
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          python create_pr_comment.py --token ${{ secrets.GH_ACCESS_TOKEN }}
          echo "Okay!"

