name: PR Comment

on:
  pull_request:

jobs:
  PR-Comment:
    runs-on: ubuntu-latest
    steps:
    - name: PR Comment
      uses: actions/github-script@v2
    - name: Get the run URL
      run: |
            body=$(<run.txt)
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })